// <auto-generated />
using System;
using System.Collections.Generic;
using System.Xml.Serialization;

namespace BannerlordModEditor.Common.Models.Data
{
    /// <summary>
    /// 室外粒子系统配置 - particle_systems_outdoor.xml
    /// </summary>
    [XmlRoot("particle_effects")]
    public class ParticleSystemsOutdoor
    {
        [XmlElement("effect")]
        public List<Effect> Effects { get; set; } = new List<Effect>();
    }

    public class Effect
    {
        [XmlAttribute("name")]
        public string Name { get; set; }

        [XmlAttribute("guid")]
        public string Guid { get; set; }

        [XmlElement("emitters")]
        public Emitters Emitters { get; set; }

        public bool ShouldSerializeName() => !string.IsNullOrEmpty(Name);
        public bool ShouldSerializeGuid() => !string.IsNullOrEmpty(Guid);
        public bool ShouldSerializeEmitters() => Emitters != null && Emitters.EmitterList.Count > 0;
    }

    public class Emitters
    {
        [XmlElement("emitter")]
        public List<Emitter> EmitterList { get; set; } = new List<Emitter>();
    }

    public class Emitter
    {
        [XmlAttribute("name")]
        public string Name { get; set; }

        [XmlAttribute("_index_")]
        public int Index { get; set; }

        [XmlElement("flags")]
        public Flags Flags { get; set; }

        [XmlElement("parameters")]
        public Parameters Parameters { get; set; }

        public bool ShouldSerializeName() => !string.IsNullOrEmpty(Name);
        public bool ShouldSerializeFlags() => Flags != null && Flags.FlagList.Count > 0;
        public bool ShouldSerializeParameters() => Parameters != null && Parameters.ParameterList.Count > 0;
    }

    public class Flags
    {
        [XmlElement("flag")]
        public List<Flag> FlagList { get; set; } = new List<Flag>();
    }

    public class Flag
    {
        [XmlAttribute("name")]
        public string Name { get; set; }

        [XmlAttribute("value")]
        public string Value { get; set; }

        public bool ShouldSerializeName() => !string.IsNullOrEmpty(Name);
        public bool ShouldSerializeValue() => !string.IsNullOrEmpty(Value);
    }

    public class Parameters
    {
        [XmlElement("parameter")]
        public List<Parameter> ParameterList { get; set; } = new List<Parameter>();
    }

    public class Parameter
    {
        [XmlAttribute("name")]
        public string Name { get; set; }

        [XmlAttribute("value")]
        public string Value { get; set; }

        [XmlAttribute("base")]
        public string Base { get; set; }

        [XmlAttribute("bias")]
        public string Bias { get; set; }

        [XmlElement("curve")]
        public Curve Curve { get; set; }

        [XmlElement("color")]
        public ColorElement Color { get; set; }

        [XmlElement("alpha")]
        public AlphaElement Alpha { get; set; }

        [XmlElement("keys")]
        public Keys Keys { get; set; }

        public bool ShouldSerializeName() => !string.IsNullOrEmpty(Name);
        public bool ShouldSerializeValue() => !string.IsNullOrEmpty(Value);
        public bool ShouldSerializeBase() => !string.IsNullOrEmpty(Base);
        public bool ShouldSerializeBias() => !string.IsNullOrEmpty(Bias);
        public bool ShouldSerializeCurve() => Curve != null;
        public bool ShouldSerializeColor() => Color != null;
        public bool ShouldSerializeAlpha() => Alpha != null;
        public bool ShouldSerializeKeys() => Keys != null && Keys.KeyList.Count > 0;
    }

    public class Curve
    {
        [XmlAttribute("name")]
        public string Name { get; set; }

        [XmlAttribute("version")]
        public string Version { get; set; }

        [XmlAttribute("default")]
        public string Default { get; set; }

        [XmlAttribute("curve_multiplier")]
        public string CurveMultiplier { get; set; }

        [XmlElement("keys")]
        public Keys Keys { get; set; }

        public bool ShouldSerializeName() => !string.IsNullOrEmpty(Name);
        public bool ShouldSerializeVersion() => !string.IsNullOrEmpty(Version);
        public bool ShouldSerializeDefault() => !string.IsNullOrEmpty(Default);
        public bool ShouldSerializeCurveMultiplier() => !string.IsNullOrEmpty(CurveMultiplier);
        public bool ShouldSerializeKeys() => Keys != null && Keys.KeyList.Count > 0;
    }

    public class Keys
    {
        [XmlElement("key")]
        public List<Key> KeyList { get; set; } = new List<Key>();
    }

    public class Key
    {
        [XmlAttribute("time")]
        public string Time { get; set; }

        [XmlAttribute("value")]
        public string Value { get; set; }

        [XmlAttribute("tangent")]
        public string Tangent { get; set; }

        public bool ShouldSerializeTime() => !string.IsNullOrEmpty(Time);
        public bool ShouldSerializeValue() => !string.IsNullOrEmpty(Value);
        public bool ShouldSerializeTangent() => !string.IsNullOrEmpty(Tangent);
    }

    public class ColorElement
    {
        [XmlElement("keys")]
        public Keys Keys { get; set; }
        public bool ShouldSerializeKeys() => Keys != null && Keys.KeyList.Count > 0;
    }

    public class AlphaElement
    {
        [XmlElement("keys")]
        public Keys Keys { get; set; }
        public bool ShouldSerializeKeys() => Keys != null && Keys.KeyList.Count > 0;
    }
}